# Generated by Django 4.1.7 on 2023-09-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('sub_category', models.CharField(max_length=50)),
                ('prize', models.CharField(max_length=10)),
                ('desc', models.CharField(max_length=350)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(upload_to='static/img/products')),
            ],
        ),
    ]
