# Generated by Django 4.1.7 on 2023-09-24 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clothingstore', '0005_rename_image_product_image1_product_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image1',
            new_name='image',
        ),
    ]
