# Generated by Django 4.1.7 on 2023-09-24 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clothingstore', '0006_rename_image1_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image4',
        ),
    ]
