# Generated by Django 4.1.7 on 2023-09-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clothingstore', '0007_remove_product_image2_remove_product_image3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/products')),
                ('prize', models.CharField(max_length=10)),
            ],
        ),
    ]
