# Generated by Django 4.1.7 on 2023-10-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clothingstore', '0018_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='p_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
