# Generated by Django 4.1.7 on 2023-10-01 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clothingstore', '0020_checkout_p_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='p_name',
        ),
    ]
