# Generated by Django 4.1.7 on 2023-10-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clothingstore', '0022_checkout_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='image',
            field=models.ImageField(default=0, upload_to='images/Verfication'),
            preserve_default=False,
        ),
    ]
