# Generated by Django 4.1.7 on 2023-10-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clothingstore', '0023_checkout_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='answer',
            field=models.CharField(max_length=100),
        ),
    ]
