# Generated by Django 4.1.7 on 2023-10-01 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clothingstore', '0024_alter_checkout_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='image',
        ),
    ]
