# Generated by Django 4.1.7 on 2023-10-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clothingstore', '0025_remove_checkout_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=100)),
                ('messsage', models.CharField(max_length=5000)),
            ],
        ),
        migrations.DeleteModel(
            name='cart',
        ),
    ]
