# Generated by Django 4.1.7 on 2023-10-01 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clothingstore', '0026_contact_delete_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='messsage',
            new_name='message',
        ),
    ]
